src/objects/Author__c.object
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Author Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/book__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Book_Author__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Author</label>
        <referenceTo>Author__c</referenceTo>
        <relationshipLabel>Book Authors</relationshipLabel>
        <relationshipName>Book_Authors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Book</label>
        <referenceTo>book__c</referenceTo>
        <relationshipLabel>Book Authors</relationshipLabel>
        <relationshipName>Book_Authors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Book Author</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Book Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Book_Genre__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Book</label>
        <referenceTo>book__c</referenceTo>
        <relationshipLabel>Book Genres</relationshipLabel>
        <relationshipName>Book_Genres</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genre1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipLabel>Book Genres</relationshipLabel>
        <relationshipName>Book_Genres</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Book Genre</label>
    <nameField>
        <displayFormat>BG-{000000}</displayFormat>
        <label>Book Genre Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Genre__c.object
<CustomObject>
    <label>Genre</label>
    <nameField>
        <label>Genre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BooksSelector.cls
public with sharing class BooksSelector {
    @AuraEnabled
    public String recordId;
    @AuraEnabled
    public String bookName;
    @AuraEnabled
    public List<BookGenres> bookGenres;
    @AuraEnabled
    public List<BookAuthor> bookAuthors;
    @AuraEnabled
    public Decimal price;
    


    public BooksSelector(String recId) {
        this.recordId = recId;
    }
    


    public static List<BooksSelector> getBooks(Integer pSize,Integer offset,String orderBy)
    {
        List<BooksSelector> bookForPage = new List<BooksSelector>();

        List<Book__c> books = Database.query('SELECT Name,Price__c,'+
                    		'(SELECT genre1__r.name FROM Book_genres__r),'+
                    		'(SELECT author__r.name FROM Book_authors__r)'+
                             '  FROM Book__c '+
                               'ORDER BY '+orderBy +
                               ' LIMIT '+ pSize +' OFFSET '+offset); 

        for (Book__c book: books)
        {
            BooksSelector oneBook = new BooksSelector(book.Id);
          List<BookGenres> bookGenres = new List<BookGenres>();
          List<BookAuthor> bookAuthors = new List<BookAuthor>();
          for (Book_Genre__c bookGenre: book.Book_Genres__r){
                BookGenres genreForBook = new BookGenres();
                genreForBook.recordId = bookGenre.Genre1__r.Id;
                genreForBook.genreName = bookGenre.Genre1__r.Name;
                bookGenres.add(genreForBook);
            }
            for (Book_Author__c bookAuthor: book.Book_Authors__r){
                BookAuthor authorForBook = new BookAuthor();
                authorForBook.recordId = bookAuthor.Author__r.Id;
                authorForBook.authorName = bookAuthor.Author__r.Name;
                bookAuthors.add(authorForBook);
            }
            oneBook.bookGenres = bookGenres;
            oneBook.bookAuthors = bookAuthors;
            oneBook.bookName = book.Name;
            oneBook.price = book.Price__c;
            bookForPage.add(oneBook);
        }
        return bookForPage;
    }

    public static Boolean deleteBookAndBookAssociated(Book__c[] objectForDelete){
        try {
            delete objectForDelete;
        } catch(Exception e) {
            throw new DmlException(e);
        }
        return true;
    }

    public static Book__c[] getBookById(Id bookId){
        Book__c[] bookForDelete = [SELECT Name,
                      (SELECT genre1__r.name FROM Book_genres__r),
                      (SELECT author__r.name FROM Book_authors__r)
                      FROM book__c
                      where id = :bookId];
        return bookForDelete;
    }
    public class BookGenres {
        @AuraEnabled
        public String genreName { get;set; }
        
        @AuraEnabled
        public String recordId { get;set; }
    }

    public class BookAuthor {
        @AuraEnabled
        public String authorName { get;set; }
        
        @AuraEnabled
        public String recordId { get;set; }

    }
}