src/objects/Author__c.object
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Author Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/book__c.object
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Book_Author__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Author</label>
        <referenceTo>Author__c</referenceTo>
        <relationshipLabel>Book Authors</relationshipLabel>
        <relationshipName>Book_Authors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Book</label>
        <referenceTo>book__c</referenceTo>
        <relationshipLabel>Book Authors</relationshipLabel>
        <relationshipName>Book_Authors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Book Author</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Book Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AuthorsSelector.cls
public class AuthorsSelector {
    @AuraEnabled
    public String recordId;
    @AuraEnabled
    public String recordName ;
    
    public AuthorsSelector(String recId) {
        this.recordId = recId;
    }
    
    public static List<AuthorsSelector> getAuthors()
    {
        List<AuthorsSelector> allAuthors = new List<AuthorsSelector>();
        List<Author__c> authors = null;

        authors = [SELECT id,name 
                    FROM Author__c
                    ORDER BY name]; 

        for (Author__c e: authors)
        {
            AuthorsSelector i = new AuthorsSelector(e.id);
            i.recordName = e.Name;

            allAuthors.add(i);
        }
        return allAuthors;
    }

    public static AuthorsSelector addAuthorToBook(Id bookId,Id authorId)
    {
        Book_Author__c bookAuthor;
        try {
            bookAuthor = new Book_Author__c(Book__c = bookId, Author__c = authorId);
            insert bookAuthor;
        } catch(Exception e) {
            throw new DmlException(e);
        }

        AuthorsSelector newAuthor = new AuthorsSelector(bookAuthor.id);

        return newAuthor;
    }
}