src/objects/Author__c.object
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Author Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/book__c.object
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Book_Author__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Author</label>
        <referenceTo>Author__c</referenceTo>
        <relationshipLabel>Book Authors</relationshipLabel>
        <relationshipName>Book_Authors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Book</label>
        <referenceTo>book__c</referenceTo>
        <relationshipLabel>Book Authors</relationshipLabel>
        <relationshipName>Book_Authors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Book Author</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Book Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Book_Genre__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Book</label>
        <referenceTo>book__c</referenceTo>
        <relationshipLabel>Book Genres</relationshipLabel>
        <relationshipName>Book_Genres</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genre1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipLabel>Book Genres</relationshipLabel>
        <relationshipName>Book_Genres</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Book Genre</label>
    <nameField>
        <displayFormat>BG-{000000}</displayFormat>
        <label>Book Genre Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/actionsController.cls
public with sharing class actionsController {
    
    @AuraEnabled
    public static AuthorsSelector addNewAuthorToBook(Id bookId,Id authorId){

        String[] fieldsToCheck = new String[] {'Book__c','Author__c'};
        AuthorsSelector newAuthor;
        
        Boolean bookAuthorAccess = ObjectAndFieldsAccessCheck.checkAccessToObject('Book_Author__c','isCreateable');
        Boolean bookAuthorFieldsAccess = ObjectAndFieldsAccessCheck.checkAccessToObjectFields('Book_Author__c','isCreateable',fieldsToCheck);

        try{
            if(bookAuthorAccess &&
                bookAuthorFieldsAccess){
                newAuthor = AuthorsSelector.addAuthorToBook(bookId,authorId);
            }else{
                throw new AuraHandledException(Config.errorMsg(1));
            }
        }catch(DmlException e){
            throw new AuraHandledException(Config.errorMsg(4));
        }
        return newAuthor;
        
    }
    
    @AuraEnabled
    public static GenresSelector AddNewGenreToBook(Id bookId,Id genreId){
        String[] fieldsToCheck = new String[] {'Book__c','Genre1__c'};

        GenresSelector newGenre;
        
        Boolean bookAuthorAccess = ObjectAndFieldsAccessCheck.checkAccessToObject('Book_Genre__c','isCreateable');
        Boolean bookAuthorFieldsAccess = ObjectAndFieldsAccessCheck.checkAccessToObjectFields('Book_Genre__c','isCreateable',fieldsToCheck);

        try{
            if(bookAuthorAccess &&
                bookAuthorFieldsAccess){
                newGenre = GenresSelector.addAuthorToBook(bookId,genreId);
            }else{
                throw new AuraHandledException(Config.errorMsg(1));
            }
        }catch(DmlException e){
            throw new AuraHandledException(Config.errorMsg(4));
        }
        return newGenre;
    }
    
    @AuraEnabled
    public static Boolean deleteBook(Id bookIdForDelete){
        Boolean deleteResult;
        Book__c[] bookForDelete;
        Boolean bookDeleteAccess = ObjectAndFieldsAccessCheck.checkAccessToObject('Book__c','isDeletable');

        try{
            if(bookDeleteAccess ){
                bookForDelete = BooksSelector.getBookById(bookIdForDelete);
                deleteResult = BooksSelector.deleteBookAndBookAssociated(bookForDelete);
            }else{
                throw new AuraHandledException(Config.errorMsg(5));
            }
        }catch(DmlException e){
            throw new AuraHandledException(Config.errorMsg(6));
        }
        return deleteResult;
    }
}