src/objects/Author__c.object
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Author Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/book__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Book_Author__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Author</label>
        <referenceTo>Author__c</referenceTo>
        <relationshipLabel>Book Authors</relationshipLabel>
        <relationshipName>Book_Authors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Book</label>
        <referenceTo>book__c</referenceTo>
        <relationshipLabel>Book Authors</relationshipLabel>
        <relationshipName>Book_Authors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Book Author</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Book Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Book_Genre__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Book</label>
        <referenceTo>book__c</referenceTo>
        <relationshipLabel>Book Genres</relationshipLabel>
        <relationshipName>Book_Genres</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genre1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipLabel>Book Genres</relationshipLabel>
        <relationshipName>Book_Genres</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Book Genre</label>
    <nameField>
        <displayFormat>BG-{000000}</displayFormat>
        <label>Book Genre Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Genre__c.object
<CustomObject>
    <label>Genre</label>
    <nameField>
        <label>Genre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/bookAndBookAsssociatedRecordsSelector.cls
public class bookAndBookAsssociatedRecordsSelector {
    
    private String errMsg;
    
    public List<Genre__c> getAllGenres(){
         String[] fieldsToCheck = new String[] {'Name'};
             Genre__c[] result = null;
             Boolean genreAccess = ObjectAndFieldsAccessCheck.checkAccessToObject('Genre__c','isAccessible');
             Boolean genreFieldsAccess = ObjectAndFieldsAccessCheck.checkAccessToObjectFields('Genre__c','isAccessible',fieldsToCheck);
        try{
            if(genreAccess &&
                genreFieldsAccess){
                result = [SELECT name from Genre__c];
            }else{
                this.setErrMsg(0);
            }
        }catch(DMLException e){
            this.setErrMsg(2);
            return null;
        }
        
        return result;
    }
    
    public String getErrMsg(){
        return errMsg;
    }
    
    public List<Author__c> getAllAuthors(){
        String[] fieldsToCheck = new String[] {'Name'};
        Author__c[] result = null;
        Boolean authorAccess = ObjectAndFieldsAccessCheck.checkAccessToObject('Author__c','isAccessible');
        Boolean authorFieldsAccess = ObjectAndFieldsAccessCheck.checkAccessToObjectFields('Author__c','isAccessible',fieldsToCheck);
        try{
            if(authorAccess &&
                authorFieldsAccess){
                result = [SELECT name from Author__c];
            }else{
                this.setErrMsg(3);
            }
        }catch(DMLException e){
            this.setErrMsg(2);
            return null;
        }
        
        return result;
    }

    public List<Map<String,String>> actionsWithBooks(){
        // List<Map<String,String>>
        List<Map<String,String>> actions = new List<Map<String,String>>();
        String[] bookAuthorFields = new String[] {'Book__c','Author__c'};
        String[] bookGenreFields = new String[] {'Book__c','Genre1__c'};
        String[] bookFields = new String[] {'Name','Price__c'};

        Boolean bookUpdateAccess = ObjectAndFieldsAccessCheck.checkAccessToObject('Book__c','isUpdateable');
        Boolean bookDeleteAccess = ObjectAndFieldsAccessCheck.checkAccessToObject('Book__c','isDeletable');
        Boolean bookFieldsAccess = ObjectAndFieldsAccessCheck.checkAccessToObjectFields('Book__c','isUpdateable',bookFields);
        Boolean bookAuthorAccess = ObjectAndFieldsAccessCheck.checkAccessToObject('Book_Author__c','isCreateable');
        Boolean bookAuthorFieldsAccess = ObjectAndFieldsAccessCheck.checkAccessToObjectFields('Book_Author__c','isCreateable',bookAuthorFields);
        Boolean bookGenreAccess = ObjectAndFieldsAccessCheck.checkAccessToObject('Book_Genre__c','isCreateable');
        Boolean bookGenreFieldsAccess = ObjectAndFieldsAccessCheck.checkAccessToObjectFields('Book_Genre__c','isCreateable',bookGenreFields);

        // String objectForCheck = 'Book_Author__c';

        if(bookUpdateAccess &&
            bookFieldsAccess){
                Map<String, String> addGenre = new Map<String, String>();
                addGenre.put('label','Edit');
                addGenre.put('value','edit');
                actions.add(addGenre);
            }

        if(bookAuthorAccess &&
            bookAuthorFieldsAccess){
                Map<String, String> addAuthor = new Map<String, String>();
                addAuthor.put('label','Add Author To Book');
                addAuthor.put('value','addAuthor');
                actions.add(addAuthor);
            }

        if(bookGenreAccess &&
            bookGenreFieldsAccess){
                Map<String, String> addGenre = new Map<String, String>();
                addGenre.put('label','Add Genre To Book');
                addGenre.put('value','addGenre');
                actions.add(addGenre);
            }
            
        if(bookDeleteAccess){
                Map<String, String> addGenre = new Map<String, String>();
                addGenre.put('label','Delete Book');
                addGenre.put('value','delete');
                actions.add(addGenre);
            }

        return actions;
    }
    
    private void setErrMsg(Integer errCode){
        Map<Integer,String> errors= new Map<Integer,String> {0=>'Do not have access to Genre fields or object',
        1=>'Do not have access to edit record',
        2=>'Somthing wrong with Record',
        3=>'Do not have access to Author fields or object'};
        this.errMsg = errors.get(errCode);
    }
    // public Boolean checkAccessToObjectFields(String objectName,String accessType,List<String> fieldsToCheck){
        
    //     SObjectType schemaType = Schema.getGlobalDescribe().get(objectName);
    //     Map<String, SObjectField> objectFieldMap = schemaType.getDescribe().fields.getMap();

    //     if(accessType == 'isAccessible'){
    //         for (String fieldToCheck : fieldsToCheck) {
    //             if (!objectFieldMap.get(fieldToCheck).getDescribe().isAccessible()) {
    //                 return false;
    //             }
    //         }
    //     }
        
    //     if(accessType == 'isCreateable'){
    //         for (String fieldToCheck : fieldsToCheck) {
    //             if (!objectFieldMap.get(fieldToCheck).getDescribe().isCreateable()) {
    //                 return false;
    //             }
    //         }
    //     }
    //     if(accessType == 'isUpdateable'){
    //         for (String fieldToCheck : fieldsToCheck) {
    //             if (!objectFieldMap.get(fieldToCheck).getDescribe().isUpdateable()) {
    //                 return false;
    //             }
    //         }
    //     }
        
    //     return true;
    // }

    // public Boolean checkAccessToObject(String objectName,String accessType){
        
    //     if(accessType == 'isAccessible'){
    //         if(!Schema.getGlobalDescribe().get(objectName).getDescribe().isAccessible()){
    //             return false;
    //         }
    //     }
        
    //     if(accessType == 'isCreateable'){
    //         if(!Schema.getGlobalDescribe().get(objectName).getDescribe().isCreateable()){
    //             return false;
    //         }
    //     }
        
    //     if(accessType == 'isUpdateable'){
    //         if(!Schema.getGlobalDescribe().get(objectName).getDescribe().isUpdateable()){
    //             return false;
    //         }
    //     }
        
    //     if(accessType == 'isDeletable'){
    //         if(!Schema.getGlobalDescribe().get(objectName).getDescribe().isDeletable()){
    //             return false;
    //         }
    //     }
    //     return true;
    // }

}