src/objects/book__c.object
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Book_Genre__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Book</label>
        <referenceTo>book__c</referenceTo>
        <relationshipLabel>Book Genres</relationshipLabel>
        <relationshipName>Book_Genres</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genre1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipLabel>Book Genres</relationshipLabel>
        <relationshipName>Book_Genres</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Book Genre</label>
    <nameField>
        <displayFormat>BG-{000000}</displayFormat>
        <label>Book Genre Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Genre__c.object
<CustomObject>
    <label>Genre</label>
    <nameField>
        <label>Genre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GenresSelector.cls
public class GenresSelector {
    @AuraEnabled
    public String recordId;
    @AuraEnabled
    public String recordName ;
    
    public GenresSelector(String recId) {
        this.recordId = recId;
    }
    
    public static List<GenresSelector> getGenres()
    {
        List<GenresSelector> allGenres = new List<GenresSelector>();
        List<Genre__c> genres = null;

        genres = [SELECT id,name 
                    FROM Genre__c
                    ORDER BY name]; 
                    
        for (Genre__c e: genres)
        {
            GenresSelector i = new GenresSelector(e.id);
            i.recordName = e.Name;

            allGenres.add(i);
        }
        return allGenres;
    }

    public static GenresSelector addAuthorToBook(Id bookId,Id genreId)
    {
        Book_Genre__c bookRenre;
        try {
            bookRenre = new Book_Genre__c(Book__c = bookId, Genre1__c = genreId);
            insert bookRenre;
        } catch(Exception e) {
            throw new DmlException(e);
        }

        GenresSelector newGenre = new GenresSelector(bookRenre.id);

        return newGenre;
    }
}